import Head from "next/head";
import apiClient from "@/lib/apiClient";
import PagenationPosts from "@/components/Pagenation/PagenationPosts";
import { NUMBER_OF_POSTS_PER_PAGE } from "@/constants/constants";
import { useEffect, useState } from "react";
import Pagenation from "@/components/Pagenation/Pagenation";
import { postType } from "@/types";

export const getServerSideProps = async (context: any) => {
  try {
    const res = await apiClient.get("/posts");
    const posts = res.data;
    const currentPageNumber = context.params.page;
    const startIndex = (currentPageNumber - 1) * NUMBER_OF_POSTS_PER_PAGE;
    const endIndex = startIndex + NUMBER_OF_POSTS_PER_PAGE;
    const slicedPosts = posts.slice(startIndex, endIndex);
    if (parseInt(currentPageNumber) > Math.floor(posts.length / NUMBER_OF_POSTS_PER_PAGE) + (posts.length % NUMBER_OF_POSTS_PER_PAGE > 0 ? 1 : 0)) {
      return { notFound: true };
    }

    return {
      props: {
        allPosts: posts,
        posts: slicedPosts,
      },
    };
  } catch (err) {
    console.log(err);
  }
};

const BlogPageList = ({ allPosts, posts }: any) => {
  const [pageCount, setPageCount] = useState(0);

  useEffect(() => {
    const getPageCount = () => {
      // 11/4= 4.2=mfで 4, 11% 4 = 2あまり2,余が出るから1
      const pageNumber = Math.floor(allPosts.length / NUMBER_OF_POSTS_PER_PAGE) + (allPosts.length % NUMBER_OF_POSTS_PER_PAGE > 0 ? 1 : 0);
      setPageCount(pageNumber);
    };
    getPageCount();
  });

  return (
    <>
      <Head>
        <title>You planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="min-h-screen py-8">
          <main className="lg:grid grid-cols-2 mx-4">
            {posts.map((post: any) => (
              <PagenationPosts key={post.id} post={post} />
            ))}
          </main>
          <Pagenation pageCount={pageCount} />
        </div>
      </div>
    </>
  );
};

export default BlogPageList;
