import Head from "next/head";
import PagenationPosts from "@/components/Pagenation/PagenationPosts";
import { NUMBER_OF_POSTS_PER_PAGE } from "@/constants/constants";
import { useEffect, useState } from "react";
import Pagenation from "@/components/Pagenation/Pagenation";
import { GetServerSidePropsContext, PreviewData } from "next";
import { ParsedUrlQuery } from "querystring";
import { postType } from "@/types";
import { allPosts } from "@/pages/api/functions/post";

//pagenationページ
export const getServerSideProps = async (context: GetServerSidePropsContext<ParsedUrlQuery, PreviewData>) => {
  try {
    const posts = await allPosts();
    const pageQueryParam = Array.isArray(context.query.page) ? context.query.page[0] : context.query.page || "";
    const currentPageNumber = parseInt(pageQueryParam);
    const startIndex = (currentPageNumber - 1) * NUMBER_OF_POSTS_PER_PAGE;
    const endIndex = startIndex + NUMBER_OF_POSTS_PER_PAGE;
    const slicedPosts = posts.slice(startIndex, endIndex);
    if (currentPageNumber > Math.floor(posts.length / NUMBER_OF_POSTS_PER_PAGE) + (posts.length % NUMBER_OF_POSTS_PER_PAGE > 0 ? 1 : 0)) {
      return { notFound: true };
    }

    return {
      props: {
        allPosts: posts,
        posts: slicedPosts,
      },
    };
  } catch (err) {
    console.log(err);
  }
};

interface Props {
  allPosts: postType[];
  posts: postType[];
}

const BlogPageList = ({ allPosts, posts }: Props) => {
  const [pageCount, setPageCount] = useState(0);

  useEffect(() => {
    const getPageCount = () => {
      const pageNumber = Math.floor(allPosts.length / NUMBER_OF_POSTS_PER_PAGE) + (allPosts.length % NUMBER_OF_POSTS_PER_PAGE > 0 ? 1 : 0);
      setPageCount(pageNumber);
    };
    getPageCount();
  });

  return (
    <>
      <Head>
        <title>You planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="min-h-screen py-8">
          <main className="lg:grid grid-cols-2 mx-4">
            {posts.map((post: postType) => (
              <PagenationPosts key={post.id} post={post} />
            ))}
          </main>
          <Pagenation pageCount={pageCount} />
        </div>
      </div>
    </>
  );
};

export default BlogPageList;
