import Head from "next/head";
import Post from "@/components/Post";
import Link from "next/link";
import { postType } from "@/types";
import { fivePosts } from "./api/functions/post";

export const getServerSideProps = async () => {
  try {
    const posts = await fivePosts();
    return {
      props: {
        posts,
      },
    };
  } catch (err) {
    console.log(err);
  }
};

interface Props {
  posts: postType[];
}

export default function Home({ posts }: Props) {
  return (
    <>
      <Head>
        <title>You planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen py-8">
        <main className=" container mx-auto py-4">
          {posts.map((post: postType) => (
            <Post key={post.id} post={post} />
          ))}
          <Link href="/posts/Page/1" className=" mb-6 rounded-md px-5 block text-right ">
            ...もっと見る
          </Link>
        </main>
      </div>
    </>
  );
}
